# Generated by Django 4.1.7 on 2023-06-11 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default=None, max_length=500)),
                ('schema_name', models.CharField(default=None, max_length=500)),
                ('schema_id', models.CharField(default=None, max_length=500)),
                ('cred_def_id', models.CharField(default=None, max_length=500)),
                ('attributes', models.JSONField(default=None)),
                ('version', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(default=None, max_length=500)),
                ('userId', models.CharField(default=None, max_length=500)),
                ('walletId', models.CharField(default=None, max_length=500)),
                ('email', models.CharField(default=None, max_length=500)),
                ('verkey', models.CharField(default=None, max_length=500)),
                ('role', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.UUIDField(default=uuid.uuid4)),
                ('issuer_to_holder_conn', models.CharField(default=None, max_length=500, null=True)),
                ('holder_to_issuer_conn', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
