# Generated by Django 4.1.7 on 2023-06-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holder_to_verifier_conn',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verifier_to_holder_conn',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
