# Generated by Django 4.1.7 on 2023-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_holder_to_verifier_conn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='msp_id',
            field=models.CharField(default='Org1MSP', max_length=500, null=True),
        ),
    ]
