# Generated by Django 4.1.7 on 2024-01-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_msp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='msp_id',
            new_name='mspId',
        ),
    ]
